Switch filtered column to a numeric one. fixes #160
datacarpentry/genomics-r-intro pull request #161
Opened 2022-11-09 16:16 UTC by ytakemon

Currently, we filter on INDEL which is a logical column: `filter(variants, sample_id == "SRR2584863", (INDEL | QUAL >= 100))` and INDEL is logical. Instead of INDEL, we will now filter on MQ: `filter(variants, sample_id == "SRR2584863", (MQ >= 50 | QUAL >= 100))`

2022-11-09 17:09 UTC, ytakemon commented
Did not know you could "draft" a pull request to indicate it is not yet ready for merging! Very cool!

2023-01-11 16:50 UTC, ytakemon commented
All issues listed under "Data wrangling and analysis with tidyverse"  in our mega issue: #142 has been addressed and is now ready for review. Pinging @JasonJWilliamsNY @naupaka and @poterlowicz-lab (whoever has a moment) to review and merge.

2023-01-11 17:11 UTC, naupaka requested changes
Nice work @ytakemon! I spotted one minor thing to fix.

2023-01-12 23:46 UTC, ytakemon commented on _episodes_rmd/05-dplyr.Rmd
> +> It may be temping to install the `tidyverse` packages, as it contains many
Fixed in [5925ee7](https://github.com/datacarpentry/genomics-r-intro/pull/161/commits/5925ee76d57e8f0b36e3fb08063e9f770f5d1ef5)

2023-01-13 22:48 UTC, naupaka approved these changes

2023-01-13 22:48 UTC, merged